version: "3.5"

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    restart: on-failure
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/app
